### PR TITLE
Fixed most spelling errors

### PR DESCRIPTION
**Pull request by AbdoShakush**
Going to check out the other chapters one at a time and fix whatever I find.

### CODE REVIEW

**Comment by mdubbs** [comment]
A lot of these changes are a shift to US spelling, and I am not sure they are needed. There are, however, actual spelling corrections as well.

**Comment by AbdoShakush** [comment]
I did hesitate between leaving British English spelling or turning it all into US English, in the end I just went with it. If needed, I can revert the British > US changes and leave only the proper corrections. Going to let Ben decide.

**Comment by jturbo26** [comment]
You got the one I came here to fix. Termianl. Good job!

**Comment by benwalks** [comment]
This is great guys, thanks.  I don't really care about English / Australian / US so let's just merge the changes.

For the record, 'thang' was on purpose.

**Pull request merged**
